import React, {Component} from 'react';
import axios from 'axios';
import './LoginView.css';

export default class RegisterView extends Component {
    constructor(props) {
        super(props);
        this.state = {
            email: null,
            password: null
        }
    }

    /**
     * Method that handles email input change
     * @param event the event generated by the tag
     */
    onEmailChange(event) {
        this.setState({email: event.target.value})
    }

    /**
     * Method that handles password input change
     * @param event the event generated by the tag
     */
    onPasswordChange(event) {
        this.setState({password: event.target.value})
    }

    /**
     * Method that submits the login attempt to the server
     * @param event the event generated by the button
     */
    onSubmitLogin(event) {
        event.preventDefault();
        let user = {
            username: this.state.email,
            password: this.state.password
        };
        axios.get('localhost/API/loginUser',{user})
            .then((res)=>{
               return res.json();
            })
            .then((res)=>{
                console.log(res)
            });
    }

    render() {
        return (
            <div id="login">
                <div className="row justify-content-around">
                    <div className="col-sm-3 col-lg-4"/>
                    <div className="col-sm-6 col-lg-4">
                        <article className="card-body">
                            <h4 className="card-title text-center mb-4 mt-1">Ingresar</h4>
                            <hr/>
                            <p className="text-success text-center">Some message goes here</p>
                            <form>
                                <div className="form-group">
                                    <div className="input-group">
                                        <div className="input-group-prepend">
                                            <span className="input-group-text">
                                                <i className="fa fa-envelope"/>
                                            </span>
                                        </div>
                                        <input name="" className="form-control" placeholder="Correo electrónico"
                                               type="email" onChange={this.onEmailChange.bind(this)}/>
                                    </div>
                                </div>
                                <div className="form-group">
                                    <div className="input-group">
                                        <div className="input-group-prepend">
                                            <span className="input-group-text"> <i className="fa fa-lock"/> </span>
                                        </div>
                                        <input className="form-control" placeholder="******" type="password"
                                               onChange={this.onPasswordChange.bind(this)}/>
                                    </div>
                                </div>
                                <div className="form-group">
                                    <button type="submit" className="btn btn-success btn-block"
                                            onClick={this.onSubmitLogin.bind(this)}> Login
                                    </button>
                                </div>
                            </form>
                        </article>
                    </div>
                    <div className="col-sm-3 col-lg-4"/>
                </div>
            </div>
        );
    }
}