import React, {Component} from 'react';
import axios from 'axios';
import './LoginView.css';
import PropTypes from 'prop-types';
import Cookies from 'universal-cookie';

export default class LoginView extends Component {
    constructor(props) {
        super(props);
        this.state = {
            email: null,
            password: null,
            message: null
        }
    }

    /**
     * Method that handles email input change
     * @param event the event generated by the tag
     */
    onEmailChange(event) {
        this.setState({email: event.target.value})
    }

    /**
     * Method that handles password input change
     * @param event the event generated by the tag
     */
    onPasswordChange(event) {
        this.setState({password: event.target.value})
    }

    /**
     * Method that submits the login attempt to the server
     * @param event the event generated by the button
     */
    onSubmitLogin(event) {
        event.preventDefault();
        let user = {
            email: this.state.email,
            password: this.state.password
        };
        axios.post('/API/loginUser', user)
            .then((res) => {
                console.log(res);
                return res.data;
            })
            .then((data) => {
                console.log(data);
                this.setState({message: data.message});
                this.props.updateAuth(data.auth);
                if (data.auth) {
                    let cookies = new Cookies();
                    cookies.set("EVENT_APP_TOKEN_COOKIE", data.token, {path: '/'});
                    cookies = new Cookies();
                    cookies.set("EVENT_APP_ID_COOKIE", data.id, {path: '/'});
                    this.props.getEvents();
                }
            })
            .catch((err) => {
                console.log(err);
            });
    }

    render() {
        return (
            <div id="login">
                <div className="row justify-content-around">
                    <div className="col-sm-3 col-lg-4"/>
                    <div className="col-sm-6 col-lg-4">
                        <article className="card-body">
                            <h4 className="card-title text-center mb-4 mt-1">Ingresar</h4>
                            <hr/>
                            {
                                this.state.message ?
                                    <p className="text-success text-center">{this.state.message}</p>
                                    : null
                            }
                            <form>
                                <div className="form-group">
                                    <div className="input-group">
                                        <div className="input-group-prepend">
                                            <span className="input-group-text">
                                                <i className="fa fa-envelope"/>
                                            </span>
                                        </div>
                                        <input name="" className="form-control" placeholder="Correo electrónico"
                                               type="email" onChange={this.onEmailChange.bind(this)}/>
                                    </div>
                                </div>
                                <div className="form-group">
                                    <div className="input-group">
                                        <div className="input-group-prepend">
                                            <span className="input-group-text"> <i className="fa fa-lock"/> </span>
                                        </div>
                                        <input className="form-control" placeholder="******" type="password"
                                               onChange={this.onPasswordChange.bind(this)}/>
                                    </div>
                                </div>
                                <div className="form-group">
                                    <button type="submit" className="btn btn-success btn-block"
                                            onClick={this.onSubmitLogin.bind(this)}> Login
                                    </button>
                                </div>
                            </form>
                        </article>
                    </div>
                    <div className="col-sm-3 col-lg-4"/>
                </div>
            </div>
        );
    }
}

LoginView.propTypes = {
    updateAuth: PropTypes.func.isRequired,
    getEvents: PropTypes.func.isRequired
};